name: "crypto_market"
version: "1.0"
config-version: 2

profile: "crypto_market"

model-paths: ["models"]

models:
  crypto_market:
    staging:
      +materialized: view
    marts:
      +materialized: table