services:
    postgres:
        image: postgres:17
        container_name: itc6050_pg
        environment:
            POSTGRES_USER: ${DESTINATION__POSTGRES__CREDENTIALS__USERNAME}
            POSTGRES_PASSWORD: ${DESTINATION__POSTGRES__CREDENTIALS__PASSWORD}
            POSTGRES_DB: ${DESTINATION__POSTGRES__CREDENTIALS__DATABASE}
        ports:
            - "5432:5432"
        volumes:
         - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: